CREATE DATABASE cat_sys DEFAULT CHARACTER SET utf8;
USE cat_sys
CREATE TABLE `cat_roles` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) DEFAULT NULL COMMENT '角色名称',
  `note` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `createdTime` DATETIME DEFAULT NULL COMMENT '创建时间',
  `modifiedTime` DATETIME DEFAULT NULL COMMENT '修改时 间',
  `createdUser` VARCHAR(20) DEFAULT NULL COMMENT '创建 用户',
  `modifiedUser` VARCHAR(20) DEFAULT NULL COMMENT '修改用户',
  PRIMARY KEY (`id`)
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='角色' 
